### ISSUE TITLE
Youtube Videos unable to be retrieved

### ISSUE THREAD

**Issue by danmed** [glanceapp/glance#1]
2024/04/27 22:24:25 ERROR Failed to fetch youtube feed channel=UCOk-gHyjcWZNj3Br4oxwh0A error="unexpected status code 404 for https://www.youtube.com/feeds/videos.xml?channel_id=UCOk-gHyjcWZNj3Br4oxwh0A, response: <!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content=\"initial-scale=1, minimum-scale=1, width=device-width\">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That’s an error.</ins>\n  <p>The requested URL <code>/feeds/videos.xml?channel_id=UCOk-gHyjcWZNj3Br4oxwh0A</code> was not found on this server.  <ins>That’s all we know.</ins>\n"

**Comment by svilenmarkov** [comment]
Thanks for reporting the issue!

This is however an issue with YouTube's RSS feed which is outside of my control. It looks like it tends to happen every once in a while:

* https://news.ycombinator.com/item?id=39179446
* https://www.reddit.com/r/rss/comments/1blm1c3/youtube_rss_404_outage_again/
* https://github.com/RSS-Bridge/rss-bridge/issues/2113
* https://news.ycombinator.com/item?id=39181347

If it turns into a frequent occurrence I'll look into alternative methods of retrieving the latest channel uploads.
