### ISSUE TITLE
[FEATURE REQUEST] Adding option to only show error sites in Monitor widget

### ISSUE THREAD

**Issue by asonu0917** [glanceapp/glance#105]
Thanks for the effort developing this wonderful application and making it simple to use. I am trying it and find that the monitor is often too long to fit into small columns. It may be my preference only, but it will be nice to have to option to a simple overview on the error sites only.

**Comment by svilenmarkov** [comment]
Hey, thanks for the idea!

I'll have the option added to the release after the upcoming one.
