### ISSUE TITLE
[Feature Request] Ability to append domain for RSS items

### ISSUE THREAD

**Issue by SapphicMoe** [glanceapp/glance#107]
Hi there! 

So far, Glance has been great. But I encountered an issue where, if an RSS item does not have a domain for the `link` property, it takes the server's domain for the item(s).

One such example would be the Bungie.net RSS feed: https://www.bungie.net/en/rss/News
The `link` property for the latest RSS item (as of 24 May 2024) is `/7/en/News/Article/twid-05-23-24`.

So I'm getting:
`https://home.mydomain.com/7/en/News/Article/twid-05-23-24`
instead of 
`https://bungie.net/7/en/News/Article/twid-05-23-24`

Is it possible to have a feature where we can manually append a domain for RSS items? Thanks!

**Comment by helloteemo** [comment]
Thanks for the issue

This is indeed a bug. We are considering how to fix it. Currently, there are three ways to fix it

1. Added baseDomain configuration for RSS projects. If the RSS link does not have a scheme, baseDomain is automatically added.
2. No new baseDomain configuration is added. If it is found that the RSS link does not have a scheme, the domain is taken from the URL as the baseDomain as the RSS link
3. Taking into account 1 and 2, the value priority is as follows RSS link > baseDomain > url domain

I personally think plan 3 is better

Please consider if this is possible? Please respond if you have a better plan

**Comment by svilenmarkov** [comment]
Hey, thanks for reporting the issue and glad to hear you've happy with Glance!

I think @helloteemo's 3rd suggestion where it automatically falls back to the base domain when it detects links starting with `/` but also gives you the option to override that behavior is optimal and shouldn't be difficult to implement. I'll have it added in the next release.

**Comment by helloteemo** [comment]
Thank you for your response and a small suggestion

It's best to determine whether you need to add a base domain by deciding whether to start with `http://` or `https://`. Some links don't start with `/`, but it does require adding a base domain
