### ISSUE TITLE
Weather widget stops app initialization

### ISSUE THREAD

**Issue by Jerakin** [glanceapp/glance#115]
# Description

If you can establish a proper connection the weather app will fail the get command and stop the app from opening. All other widgets still ensures that the webpage still loads but their widgets say that they can't load.

If you pick a location that does not exist it also stops the app from starting.

# Expected behavior
Web page still loads even if the weather app is unable to get any valid content. The weather app will be rendered without content and/or an error displayed within it.

**Comment by svilenmarkov** [comment]
Hey, thanks for reporting this!

This was (maybe foolishly) intended behavior when I initially built the weather widget but since multiple people have reported it as unexpected I'll change it so that it no longer prevents app startup with the next release.
