### ISSUE TITLE
[Feature Request] List of configurable links

### ISSUE THREAD

**Issue by domainzero** [glanceapp/glance#118]
Requesting a simple widget that can be configured to have a list of links, maybe with icons, but with no monitoring or other active stuff.  

This is to mimic the functionality of other dashboards like Flame, etc, while still retaining the other great features you've built into glance.

**Comment by svilenmarkov** [comment]
Hey, thanks for the suggestion!

This is already possible using the [bookmarks widget](https://github.com/glanceapp/glance/blob/main/docs/configuration.md#bookmarks), unless you have a different kind of design in mind?

**Comment by domainzero** [comment]
Nope. I'm just a clown and can't read. I was looking for this feature and even looked for issues thinking, "surely I can't be missing something!" but I was. Thanks for the point in the right direction.
