### ISSUE TITLE
[REQUEST] WIDGET URL

### ISSUE THREAD

**Issue by AlissonSantos95** [glanceapp/glance#12]
Morning, i loved the home page, i'm already using, easy simple and good

I have some requests to make as WIDGET URL, today wee have 

`- type: reddit
  subreddit: technology`

but it only opens on reddit.com.br, some people like to use troddit for front end and end with reddit.mydomain.com

could wee do something like this 

`      - type: reddit
            subreddit: selfhosted
            domain: reddit.mydomain.com.br`
to open the subredit on reddit.mydomain.com.br isted of reddit.com?
same to youtube or make a variable on the container to override the original url?

**Comment by knhash** [comment]
May I also suggest one more tweak, to keep the sorting order as a parameter. I want to have a view of the top posts of the day always, so having that (and noticing when something new is rising up) will be sweet.

Same for HN. Top posts of past day.

Also already using this and have plenty of ideas, and I want to contribute :) please add a contribute section.

**Comment by AlissonSantos95** [comment]
Thank you for adding this i'm happy with the outcoming, big thanks.
