### ISSUE TITLE
Feature - Add Trending Github Repositories

### ISSUE THREAD

**Issue by brishtiteveja** [glanceapp/glance#123]
It will be a cool feature to enlist the trending Github repositories from Github trending page. It will be also cool to be able to sort by day, week, month similarly. I infact found "glance" from the Trending page.

<img width="1238" alt="Screenshot 2024-06-02 at 9 05 53 PM" src="https://github.com/glanceapp/glance/assets/2281405/a4247cef-8a75-4834-8fbb-c1ec33fa34d2">

**Comment by brishtiteveja** [comment]
Seems like this is already implemented. Closing this.

**Comment by jsspen** [comment]
@brishtiteveja sorry if I'm missing something obvious but could you explain what widget can be configured to do this?
