### ISSUE TITLE
[FEATURE] Serving behind reverse proxy

### ISSUE THREAD

**Issue by fenying** [glanceapp/glance#125]
Hi, I wanna serve the glance on a sub path of an existing site, I use below configuration for nginx:

```
    location /glance {

        proxy_redirect off;
        proxy_pass http://127.0.0.1:48888/;
        proxy_http_version 1.1;
    }
```

However, the glance page uses the link of static resource like `/static/xxx`, not a path like `/glance/static/xxx`.

Can you please add some options like `base_url` to make this work?

**Comment by svilenmarkov** [comment]
Hey, thanks for the suggestion and sorry for the inconvenience!

This is something I do want to add support for, though it'll probably happen in `v0.7.0` rather than the next release.

**Comment by stleon** [comment]
is it possible to ship it in 0.6.0?

**Comment by svilenmarkov** [comment]
@stleon Yup, will do.

**Comment by yonas** [comment]
Completed in #167 . This can be closed.
