### ISSUE TITLE
[BUG] Search field text input is always white

### ISSUE THREAD

**Issue by knhash** [glanceapp/glance#131]
This makes search field text illegible while using light theme

<img width="627" alt="Screenshot 2024-06-06 at 20 18 50" src="https://github.com/glanceapp/glance/assets/8710439/9192cd16-42db-4bbb-b02f-1528107e2c0f">

**Comment by svilenmarkov** [comment]
Hey, thanks for reporting this, I'll get it fixed in the next release. In the meantime, for an immediate fix you can use the following custom CSS using the built in [`custom-css-file`](https://github.com/glanceapp/glance/blob/main/docs/configuration.md#custom-css-file) property:

```css
.search-input {
    color: var(--color-text-highlight);
}
```
