### ISSUE TITLE
RSS Text overflowing

### ISSUE THREAD

**Issue by DickenSerm** [glanceapp/glance#136]
In Issue #86 a bug with text overflowing was fixed.

Unfortunately the problem still exists. if a continuous text without spaces comes in the title of the article.

For example, I mean the text that is blue in the posted image of Issue #86 .

**Comment by svilenmarkov** [comment]
Hey, thanks for reporting this. 

I fixed the issue for the author but I forgot about the title. Honestly accounting for super long words is not something I've put much thought into so this issue might be present in other widgets as well but I'll try and patch it up wherever I can. If you notice it anywhere else feel free to leave a comment or submit a new issue, thanks!

**Comment by DickenSerm** [comment]
Perfect :) Thanks for the quick work. If I find anything else I'll let you know :)
