### ISSUE TITLE
Monitor not working for some URLs

### ISSUE THREAD

**Issue by hxck** [glanceapp/glance#14]
I have close to 30 services in Docker that I've added to small widgets, and while most of them work fine, some of them don't, for reasons I'm not entirely sure of.

First example would be [Morphos](https://github.com/danvergara/morphos) giving me `Client Error`. I can `curl` the address from the command line on my server (192.168.50.204:8084) and get some [output](https://i.imgur.com/vFb0MrN.png). [This](https://i.imgur.com/mDFT8Af.png) is the `dig` response. It shows up in Glance like [this](https://i.imgur.com/31oSwyS.png). I get similar outputs from FileBrowser, Immich, and Yamtrack, though FileBrowser and Immich are `Not Found` errors instead of `Client Error`. Looks like [this](https://i.imgur.com/HoKP75u.png). Clicking on any of these links brings me to the service in a new tab just fine.

Second example would be some of the services requiring login, but not all of them. In particular:

- Sonarr
- Radarr
- Prowlarr

These show up like [this](https://i.imgur.com/mOIYq4p.png). Other services that require authentication show up fine.

I've tried editing the `config.yml` by having it go straight to the address (ip:port), with and without a trailing slash, to subdirectories (ip:port/photos), and to login URLs. No luck with any configuration. For a more clear look, here's a complete list of services (not including ones that aren't running of course):

Services that show up OK:

- Dockge
- Ghost
- Glances
- NetAlertX
- Nginx Proxy Manager
- Plex
- Tautulli
- Sabnzbd
- Overseerr
- VaultWarden
- Wallos
- Vikunja
- FreshRSS
- FireFish
- Homebox
- OpenBooks
- Zipline

Services that don't show up OK:

- FileBrowser
- Radarr
- Sonarr
- Prowlarr
- Yamtrack
- Morphos
- Immich

Thanks for any input!

**Comment by svilenmarkov** [comment]
Hey, thanks for reporting the issue. 

I _think_ I know what the problem is. I tried being clever by doing a `HEAD` instead of a `GET` request because realistically we're not making any use of the body, however I don't think all servers support it which is probably what's happening here. I'll change it so that it does a `GET` request instead and hopefully that fixes it. Keep an eye out for a new version soon.

**Comment by svilenmarkov** [comment]
@hxck I've released version `0.2.0` which contains the change mentioned above, could you please update and see whether this fixed it for you? Thanks.

**Comment by hxck** [comment]
@svilenmarkov That did indeed fix the issue. Thanks for the speedy fix!

**Comment by svilenmarkov** [comment]
Happy to hear that worked! :D
