### ISSUE TITLE
[Request] Custom CSS Class as a property in widgets

### ISSUE THREAD

**Issue by DickenSerm** [glanceapp/glance#147]
It would be cool if you can declare Custom CSS Class as a property in widgets.

The custom css file is a nice thing, but if I e.g. If I have several of the same RSSFeed widgets, I can currently only change them all in the same way.

For example, I have an RSS feed where the same image is always included with every post. I would like to hide this image. If I do this via the widget class in my customcss file, the images are also gone in all other RSS feed widgets.

**Comment by svilenmarkov** [comment]
Hey,

Fair point, I'll add this in the next release.
