### ISSUE TITLE
[Feature Request] Autofocus search widget

### ISSUE THREAD

**Issue by tversteeg** [glanceapp/glance#170]
Could the search widget enable the [`autofocus`](https://stackoverflow.com/a/3383468) attribute, possibly with a configuration?

That way, using glance as a new-tab replacement in the browser feels more natural.

**Comment by DickenSerm** [comment]
Meinen Sie sowas? #133

**Comment by tversteeg** [comment]
Yes basically, but all the extra other features are not required for me, just the `autofocus` attribute would be enough.
