### ISSUE TITLE
Calendar, weather and markets widgets do not update when Glance webpage is used as a web app.

### ISSUE THREAD

**Issue by nikolasdmtr** [glanceapp/glance#186]
I install the Glance landing page as a web app on Brave browser.
The aformentionted widgets do not update even after 24 hours have passed.
I have to manually reload the page for them to update. 
The clock widget updates normally though.

EDIT: I think it has to do with browser settings for the specific app. Probably "background sync". I am closing this issue now.

**Comment by svilenmarkov** [comment]
This is intended behavior. The clock is the only widget which dynamically updates, the rest require a page refresh. I might consider changing this in the future and having these widgets automatically update as well.

**Comment by nikolasdmtr** [comment]
Ah, that clears things up. Thank you!

**Comment by Aerics84** [comment]
> This is intended behavior. The clock is the only widget which dynamically updates, the rest require a page refresh. I might consider changing this in the future and having these widgets automatically update as well.

I really hope you will implement a refresh for other widgets. I don't like to refresh the website to see if something is new.
