### ISSUE TITLE
Cannot get GitHub repo release: SagerNet/sing-box

### ISSUE THREAD

**Issue by laye0619** [glanceapp/glance#193]
Hello there,

I cannot get information update for GitHub repo release: SagerNet/sing-box. All other repos are working well.

Here is the log:

ERROR No live release found repository=SagerNet/sing-box url="https://api.github.com/repos/SagerNet/sing-box/releases?per_page=10"

However, there indeed several releases showing via GitHub website.

Laye

**Comment by svilenmarkov** [comment]
Hey, this is a known issue that was fixed in `v0.6.0-beta.1`. I also released `v0.5.1` just now that contains this fix. Please update to one of those versions which should resolve the issue.

**Comment by laye0619** [comment]
Thanks you so much for such a great app.
