### ISSUE TITLE
[Bug] Pi-hole API Response Contains Invalid JSON

### ISSUE THREAD

**Issue by Szymok** [glanceapp/glance#209]
## **Pi-hole API Response Contains Invalid JSON**

When fetching DNS stats at Glance from the Pi-hole API at `https://url/api.php?summaryRaw&topItems&overTimeData10mins&auth=token`, the response contains invalid JSON with the error "invalid character '<' looking for beginning of value".

![image](https://github.com/user-attachments/assets/73f8debf-942f-49db-bbbd-4a356747ab0f)

### **Expected Behavior**
The Glance should return a valid graph response with the requested DNS statistics.

### **Actual Behavior**
The API returns an HTML response instead of JSON, causing the error "invalid character '<' looking for beginning of value" when parsing the response.

### **Steps to Reproduce**
1. Set the Pi-hole API URL and token in the Glance application configuration:
```yaml
- type: dns-stats
  service: pihole
  url: https://pihole.domain.eu/
  token: YOUR_TOKEN
```
2. Run the Glance application to fetch the DNS stats.

### **Environment**
- Glance version: 0.6.0
- Pi-hole version: 5.18.3

### **Additional Information**
- The Pi-hole API endpoint is accessible and returns a valid JSON response when tested directly.
![image](https://github.com/user-attachments/assets/1cb8f4ad-fcc9-4f08-91af-2e8fc861b16e)

- The Glance application is configured to use the correct URL and token.

Please let me know if you need any other information to investigate this issue.

**Comment by svilenmarkov** [comment]
Thanks for reporting this!

I can't seem to replicate the issue on my end while using the same version of Pi-hole. Do you have a way of checking the full HTML response? I'm wondering if it's a 404 or something else. 

This might have something to do with the lack or addition of `/admin/` in the path. For me, this URL works:

```
https://url/admin/api.php?...
```

And this does not:

```
https://url/api.php?...
```

**Comment by Szymok** [comment]
OK, nvm, i found that i had in traefik configured middlewares to replace the admin and prefix to get a shorter URL. Everything works like a charm, thank you and sorry for bothering! :D

**Comment by svilenmarkov** [comment]
No problem, glad you got it sorted out. 😄
