### ISSUE TITLE
[REQUEST] Possibility to add 4 small columns?

### ISSUE THREAD

**Issue by allardhs** [glanceapp/glance#24]
Right now, as stated in the `configuration.md` it's possible to either (a) have one full + one small columns, (b) have one full + two small columns, or (c) two full columns.

It makes sense in one of my dashboards to add four small columns. Doing so right now returns an error in the log and the program fails to start.

Would it be possible to add this four small columns mode?

**Comment by svilenmarkov** [comment]
Hey, thanks for the suggestion! 

It should be possible and not that difficult, though I can't guarantee that all widgets will look appropriately as you start resizing the page. Will require thorough experimentation.

**Comment by allardhs** [comment]
The idea is to show one dashboard with monitors only. Having them all lined up small-big-small is ugly.

An alternative would be to allow monitors to display horizontally in rows of 2 or 3 (customizable), so that the page can be displayed with only two big-big columns.

Col1---- | Col2----
Widg1----| Widg2---
M1 M2 M3 | Ma Mb Mc
M4 M5    | Md Me Mf
Widg3----| Mg
M6 M7 M8 |
M9

**Comment by joel72265** [comment]
Thank you for a wonderful application

**Feature request**: I too would like to have option to have 3 full columns layout or 4 full columns layout

**Comment by svilenmarkov** [comment]
@joel72265 I may be able to add a new widget that would allow you to stack up to two widgets horizontally, you could then use that widget within two full columns to practically achieve a 4 column layout.

**Comment by joel72265** [comment]
that would be great

Users could then use the widgets Time, Search, Bookmarks ... in 1 of the 4 columns thereby taking up less space instead of the full page width :)
