### ISSUE TITLE
New Feature: Digital Clock to show AM PM

### ISSUE THREAD

**Issue by joel72265** [glanceapp/glance#247]
New feature request:

Please show the AM / PM on the 12 hour digital clock for easier readability.

Thank you

**Comment by svilenmarkov** [comment]
Hey, you can change the format to 12 hours for the clock widget by setting `hour-format: 12h`. 

If you've already done this and still don't see the AM/PM then I'm assuming it's a bug, in which case could you please provide more information about your OS & browser?

**Comment by joel72265** [comment]
it was not showing before but AM / PM is showing now. 

Please close this request, thank you
