### ISSUE TITLE
[BUG] Multiple items in a list are rendered in a random order

### ISSUE THREAD

**Issue by allardhs** [glanceapp/glance#25]
This issue may occur in other lists, but for now I have only noticed it in the `stocks` widget.

When I list my stocks items in order, like such ...

![image](https://github.com/glanceapp/glance/assets/7335391/3cdfe4d0-57d2-4b03-ae17-df9a02848338)

... the order in which they are rendered in the dashboard are mixed up ;

![image](https://github.com/glanceapp/glance/assets/7335391/0b6dd106-ee04-4311-915d-2a4dd4175d8b)

I obviously would expect them to occur in the same order as has been defined in the yaml.

**Comment by svilenmarkov** [comment]
Hey, thanks for reporting this!

This is actually a feature, one that currently has no way of being disabled but I'll add the option to do so. They get ordered by the percent change, meaning that the stocks which had the biggest move for the day appear at the top. It was a behavior that I thought was handy but I can see why others may not.

**Comment by allardhs** [comment]
Ah yes I see. That was not understood at least by me, and I think it's not so intuitive cause as I use the dashboard longer and longer I'd be used to having the same ones on the same spot. But your suggestion to make it choosable would be the best of both worlds.
