### ISSUE TITLE
Calendar shows one day ahead.

### ISSUE THREAD

**Issue by WolfeCub** [glanceapp/glance#262]
![image](https://github.com/user-attachments/assets/45346ace-086d-4f98-a752-db5b673627ca)

Pretty much the title. I'm in EST and I notice that my calendar is a day ahead. My guess would be that this has something to do with time zones but I'm not 100% sure.

I don't see any config available for the calendar. An guidance would be greatly appreciated.

**Comment by svilenmarkov** [comment]
The calendar widget is currently rendered on the server and if Glance is running inside a container, it depends on having the correct `/etc/timezone` passed to it from the host. If you are running Glance inside a container, make sure to pass that as a volume:

```yaml
volumes:
  - /etc/timezone:/etc/timezone:ro
```

In v0.7.0 the calendar will be rendered on the client, so it should always show the correct time regardless of the server timezone.

**Comment by WolfeCub** [comment]
Ah great, I went ahead and set the `TZ` env variable and that did the trick.

Thanks!
