### ISSUE TITLE
[REQUEST] Target option for opening links & Bookmark icons.. 

### ISSUE THREAD

**Issue by Rinnray** [glanceapp/glance#30]
Hello! Love the application!

I use the application as a new tab in my browser as well, so it would be really nice if there were an option to add "targets" to widgets that have urls.
So when I click a URL I'm monitoring or a link in bookmarks, it opens it in the same tab instead of a new one, using
`target: _self`

Example from HomePage app:
![image](https://github.com/glanceapp/glance/assets/47090855/e4edd0fc-3b58-4b6c-b24c-38f114ca4d02)

It would also be really nice if there were an option to add icons for bookmarks, makes it easier and quicker when there's a lot of them.

**Comment by svilenmarkov** [comment]
Hey, thanks for the suggestions! 

Should be easy enough to add, I'll try and get both the target as well as the icons implemented for the next version.
