### ISSUE TITLE
[REQUEST] Adding a search bar

### ISSUE THREAD

**Issue by namedeleted98** [glanceapp/glance#33]
Hello!

I've been recently using glance as my dashboard what can I say other than it's AWESOME!

I really love the aesthetics and I would love for a search bar that leads to a search engine.

This is pretty amazing for a V1 projects!

Thanks in advance.

**Comment by svilenmarkov** [comment]
Hey, glad you've been enjoying using Glance and thanks for the suggestion!

I see that some people have started using it as their start page and it does make sense for it to also have a search bar. It shouldn't be too difficult to add, though likely won't happen in the next release or two as I'm trying to focus more on fixing issues and adding more customizability to current widgets.

**Comment by NotUnko** [comment]
Not sure if I should reply to this. Just wanted to say this would be a GREAT feature and I am really looking forward to it. As varunpan said, custom search engine would be amazing. For example being able to add searx or whoogle.
