### ISSUE TITLE
[REQUEST] Multi-column bookmark support

### ISSUE THREAD

**Issue by igeekbb** [glanceapp/glance#37]
There are many bookmarks, but only one column can display bookmarks in a column. I hope to add another column to display bookmarks in two or more columns side by side.

**Comment by igeekbb** [comment]
Very illogical layout
![CleanShot 2024-05-03 at 14 20 34@2x](https://github.com/glanceapp/glance/assets/154116268/a26fc8c8-5668-4753-8332-1dfaf7f3d7b2)

**Comment by svilenmarkov** [comment]
Hey, thanks for reporting this! 

Yeah, the bookmarks widget was strictly built for the `small` column and adding support for the `full` column wasn't a priority. I'll see if I can get that fixed in the next version.

**Comment by er2de2** [comment]
Can you add bookmark color font Mike bookmarks group?

**Comment by svilenmarkov** [comment]
@er2de2 Please create a new issue for this.
