### ISSUE TITLE
unexpected status code 403 for https://www.reddit.com/r/selfhosted/hot.json

### ISSUE THREAD

**Issue by Iliannnn** [glanceapp/glance#4]
I got the following with the [preconfigured page](https://github.com/glanceapp/glance/blob/main/docs/configuration.md#preconfigured-page).

![image](https://github.com/glanceapp/glance/assets/72648901/1c045ff4-c62b-47c2-8566-17109669162f)

**Comment by Iliannnn** [comment]
Put the page in an HTML viewer:
![image](https://github.com/glanceapp/glance/assets/72648901/622a0f84-a979-488b-8479-c6ecc3d528e8)

**Comment by imjuzcy** [comment]
Hosting on a VPS? Reddit blacklists data centre IPs

**Comment by imjuzcy** [comment]
This could be solved by implementing OAuth2 for the Reddit API access with user's own `client_id` and `client_secret`

**Comment by Iliannnn** [comment]
> Hosting on a VPS? Reddit blacklists data centre IPs

Yep.

**Comment by Iliannnn** [comment]
> This could be solved by implementing OAuth2 for the Reddit API access with user's own `client_id` and `client_secret`

Does Glance have an option for doing that?

**Comment by imjuzcy** [comment]
> > This could be solved by implementing OAuth2 for the Reddit API access with user's own `client_id` and `client_secret`
> 
> Does Glance have an option for doing that?

No, it's not implemented yet. In the meantime, if you have a commercial VPN subscription, you could use the IPs from them by tunnelling the traffic from Glance through them. IPs from commercial VPNs seem to be working.

**Comment by Iliannnn** [comment]
> > > This could be solved by implementing OAuth2 for the Reddit API access with user's own `client_id` and `client_secret`
> > 
> > Does Glance have an option for doing that?
> 
> No, it's not implemented yet. In the meantime, if you have a commercial VPN subscription, you could use the IPs from them by tunnelling the traffic from Glance through them. IPs from commercial VPNs seem to be working.

I do, I will do that. Thanks!

**Comment by svilenmarkov** [comment]
Thanks for offering some insight @imjuzcy, it would've taken me a while to figure out that it's a VPS issue. 

> This could be solved by implementing OAuth2 for the Reddit API access with user's own client_id and client_secret

Would this not also require having to supply your account's username and password in order to avoid having to authorize manually every time you start Glance since no data is persisted?

**Comment by imjuzcy** [comment]
> Would this not also require having to supply your account's username and password in order to avoid having to authorize manually every time you start Glance since no data is persisted?

I'm not sure that you can do this automated at all, even is username and password is provided. To get the access token, the user will need to click through a web browser. I think the requirement of having a persistent file to record the access token is unavoidable if OAuth is to be implemented.

**Comment by svilenmarkov** [comment]
I'll close this as there is now a workaround using the `request-url-template` property which allows you to route the requests through an HTTP proxy:

```yaml
- type: reddit
  request-url-template: https://your-proxy.com/{REQUEST-URL}
```

**Comment by tonylaw7** [comment]
> > > This could be solved by implementing OAuth2 for the Reddit API access with user's own `client_id` and `client_secret`
> > 
> > 
> > Does Glance have an option for doing that?
> 
> No, it's not implemented yet. In the meantime, if you have a commercial VPN subscription, you could use the IPs from them by tunnelling the traffic from Glance through them. IPs from commercial VPNs seem to be working.

What are the go to solutions for tunneling traffic as you suggested? I know gluetun is a popular choice, but are there better alternatives?
