### ISSUE TITLE
Can not get it to load

### ISSUE THREAD

**Issue by crosenblum** [glanceapp/glance#42]
Describe the bug
At first the major issue was where to create the initial configuration file, what folder path, and what is the name of that file.

According to docker configuration, you mention "glance.yml" which according to the documentation is a file, with the current configuration.

But docker set it up as a folder, so I sshed into that folder, created a file called "glance.conf" and still it will not work.

I just want to be clear what folder, to put the configuration file in, and what is the name of the file that is that configuration file.

To Reproduce

Install Glance via docker compose either raw or via portainer stack creator.
services:
glance:
image: glanceapp/glance
volumes:
- ./glance.yml:/app/glance.yml
- /etc/timezone:/etc/timezone:ro
- /etc/localtime:/etc/localtime:ro
ports:
- 8080:8080
restart: unless-stopped

All as mentioned on here:

https://github.com/glanceapp/glance?tab=readme-ov-file#installation

Create the stack, it creates the container
Then it creates this repeating error:
"failed parsing config file: read glance.yml: is a directory"

Expected behavior
If there is no default configuration file whether a default minimal version, to make sure the install went correctly, that would be useful, then I can find the file, make any changes, and start using glance.

Screenshots
https://imgur.com/a/TPqO4ac

Environement (please complete the following information)

Operating System: DietPi v9.3
Glances & psutil versions: Command does not work
How do you install Glances Docker/Portainer/Docker Compose

**Comment by svilenmarkov** [comment]
Hey, I think what happened is you ran docker compose without having a `glance.yml` file in the same directory, so docker treated the non-existent file as a directory. Give this a try:

(make sure you've cd'd into the directory where you made the `docker-compose.yml` file)

```bash
# stop and remove the container, if you haven't already
docker compose down

# remove the directory, if it exists
rm -rf glance.yml

# create the file in the same directory as the compose file
# then you can edit the file using your editor of preference
touch glance.yml

# recreate and start container again
docker compose up -d
```

> If there is no default configuration file whether a default minimal version, to make sure the install went correctly, that would be useful, then I can find the file, make any changes, and start using glance.

Not a bad idea but I'll potentially have to make a bunch of grotesquely backwards incompatible changes for this to work inside docker. I'll have to give it further thought.
