### ISSUE TITLE
[REQUEST] Custom sorting for Reddit, HackerNews

### ISSUE THREAD

**Issue by knhash** [glanceapp/glance#43]
Add option to choose custom sorting of the feed URL. 

For instance, using the url `https://news.ycombinator.com/front` instead of `https://news.ycombinator.com` gives top posts of past day in HackerNews

Similarly for Reddit

**Comment by svilenmarkov** [comment]
Hey, thanks for the suggestion. 

It's on my to-do list and I'm planning on having it released for `v0.4.0`.

**Comment by stayupthetree** [comment]
I was coming to see about having my reddit results be by new instead of the default, does this fall under the above?

**Comment by svilenmarkov** [comment]
@stayupthetree It does, and it is now possible to do in `v0.4.0`.
