### ISSUE TITLE
[REQUEST] OptionalEnvString for Monitor.Url field

### ISSUE THREAD

**Issue by devsjc** [glanceapp/glance#45]
Firstly, thanks for the great application! Very cool to see a Go-backed static site! This is less a feature request and more of a tiny modification request:

For deployments in kubernetes environments, the IP addressess of services are ephemeral, and their current value is passed into containers through environment variables. As such, in a similar manner to how the `GITHUB_TOKEN` can be parsed from environment through its use of [OptionalEnvString](https://github.com/glanceapp/glance/blob/e204029d3cc0fb96cecf7113b86fcddabef03847/internal/widget/releases.go#L12-L18), I wondered if the [`Monitor.Sites.Url`](https://github.com/glanceapp/glance/blob/e204029d3cc0fb96cecf7113b86fcddabef03847/internal/widget/monitor.go#L46-L57) field could also be an `OptionalEnvString`? That way monitors can more easily resolve to Kubernetes services.

Equally, a big part of what helps this stand out to me from the rest of the dashboard apps is it's opinionated and straightforwad nature (much like the backend language it's built with!), so not a problem if you're trying to keep things that way; I appreciate Kube is probably a niche deployment scenario.

**Comment by svilenmarkov** [comment]
Hey, not a problem, it's a small change which I can get done for the next release.
