### ISSUE TITLE
[REQUEST] Custom CSS option

### ISSUE THREAD

**Issue by jghaanstra** [glanceapp/glance#48]
It would be great to have the ability to tweak the themes a bit more, for instance an option to load custom CSS.

As usecase, I'd like a smaller margin between links in the bookmark widget. I can accomplish that with a Stylish script but I'd rather use some native Glance functionality for customization.

**Comment by svilenmarkov** [comment]
Hey, you can do this using the `custom-css-file` property on `theme`, more about that [here](https://github.com/glanceapp/glance/blob/main/docs/configuration.md#custom-css-file). Example:

```yaml
theme:
  custom-css-file: /assets/my-style.css
```

**Comment by jghaanstra** [comment]
Oh I missed that, thanx and keep up the goodf work!
