### ISSUE TITLE
[REQUEST] arm7 image

### ISSUE THREAD

**Issue by steakhutzeee** [glanceapp/glance#50]
Hi, could be possible to implement docker image for the arm7 arch?

Thank you!

**Comment by svilenmarkov** [comment]
Hey, thanks for the suggestion! I've re-pushed `v0.3.0` to include support for armv7.

**Comment by steakhutzeee** [comment]
Thank you, really appreciated!!

**Comment by steakhutzeee** [comment]
Hello again! Noted that latest image does not have armv7 variant. Is this intended?

**Comment by svilenmarkov** [comment]
Hey, not at all no, it should be there if you have a look at [the latest tag](https://hub.docker.com/r/glanceapp/glance/tags?page=&page_size=&ordering=&name=latest). I can see a `linux/arm64/v7` variant under `OS/ARCH`. 

Admittedly I did change the build and deploy process with the latest version so I'm not 100% sure that everything works as it did before. Are you getting an error from docker when trying to pull, an error when running the container or anything else?

**Comment by steakhutzeee** [comment]
Thank you for your feedback.

Yup I noted that Diun was complaining about missing manifest so I was not notified of updates.

Tried to pull just now I receive:

no matching manifest for linux/arm/v7 in the manifest list entries

**Comment by svilenmarkov** [comment]
Right, sorry about that, I'm an idiot. I forgot to remove the "64" from "linux/arm64/v7" when copying the image template.

I'll get it sorted out for future releases but for the time being you should still be able to manually pull and run the misspelled armv7 version using this command:

```
docker pull --platform linux/arm64/v7 glanceapp/glance:latest
```

**Comment by steakhutzeee** [comment]
Hey no problem! And thank you you for the immediate response!!
