### ISSUE TITLE
Issue with docker compose

### ISSUE THREAD

**Issue by wisie** [glanceapp/glance#52]
Hi there,

I'm trying to use the docker compose script provided but can't seem to get it to work. 

I've created a fresh Docker LXC using the docker compose provided with a glance.yml created in that directory. Looking at the error log in Portainer, the container is giving the following error:

"failed creating application: no pages configured"

I'm sure this is an error on my behalf and not a problem with the docker compose script. What might I be doing wrong?

Thanks in advance.

**Comment by svilenmarkov** [comment]
Hey,

Glance doesn't have a default configuration so it relies on you to tell it how you want everything to be set up. I'm assuming you've created a `glance.yml` file but haven't put anything in it? You can use the [preconfigured page](https://github.com/glanceapp/glance/blob/main/docs/configuration.md#preconfigured-page) to get started, you are free to make any changes you wish to it.

**Comment by wisie** [comment]
Ohhh that makes sense now. Thank you! I will give that a try.

**Comment by svilenmarkov** [comment]
I'll close as I'm guessing this is now resolved, feel free to leave a comment if you're still having issues!
