### ISSUE TITLE
Collapse-after property for grid-cards styled videos widget

### ISSUE THREAD

**Issue by MKwareContributions** [glanceapp/glance#58]
Title speaks for itself, it would be great to have two or three rows of videos in grid-cards style and then extend to maximum with "Show more" button, like in Twitch channels widget.

**Comment by svilenmarkov** [comment]
Hey,

Yeah I thought about that when building the style but wasn't sure about the best way to do it since it requires a different approach to the existing collapse in horizontal lists. I _think_ I have a decent idea for how to do it and I'll try to get it done for the next version.
