### ISSUE TITLE
New Feature: RSS feed Vertical Card Layout

### ISSUE THREAD

**Issue by joel72265** [glanceapp/glance#60]
Thank you for a wonderful application.

**New Feature**: please can you include a Vertical card layout for RSS feeds. This would be such a nice feature, I have included a sample card layout using a plugin. 

**Layout**
1111  aaaa  ----- 3333
2222 bbbb **** 4444
3333 cccc ##### 5555
4444 dddd %%%% 6666

![Docker Glance](https://github.com/glanceapp/glance/assets/118885352/f153458d-3966-4ae7-aac7-7d048b8237a7)

Found a similar request - https://github.com/glanceapp/glance/issues/36

**Comment by svilenmarkov** [comment]
Hey and thanks for the suggestion!

I think this is practically identical to #36 which I already have planned to do for `v0.5.0`. I'll close this for now but feel free to leave a comment if you think it differs in any way.
