### ISSUE TITLE
[REQUEST] HTML/JavaScript Widget

### ISSUE THREAD

**Issue by yefoenix** [glanceapp/glance#64]
Hello! Thanks for your work on Glance!
Could you please add the HTML/JavaScript Widget to glance,  just similar to Blogger and some other blog applications.

**Comment by svilenmarkov** [comment]
Hey and thanks for the suggestion!

It shouldn't be difficult to add, I'll see if I can get it done within the next release or two.

**Comment by yefoenix** [comment]
As a side note, this may be a general solution for some  feature requests.
e.g. simple codes for #33 Adding a search bar:
```
<form action="https://search.garudalinux.org/search">
  <div class="searchBar">
    <div class="textInput">
      <input type="text" name="q" placeholder="Search Whoogle">
    </div>
    <button type="submit" class="searchBtn">Search</button>
 </div>
 </form>
```
