### ISSUE TITLE
Weather call failing

### ISSUE THREAD

**Issue by scottjl** [glanceapp/glance#7]
https://geocoding-api.open-meteo.com/v1/search?name=chicago&count=10&language=en&format=json 

returns:

```
name	"Chicago"
country_code	"US"
```

glance.yml:

`location: Chicago, US`

This should be correct, but fails out with:

`glance  | failed parsing config file: failed fetching data for Chicago, US: no places found for Chicago, US`

**Comment by svilenmarkov** [comment]
Looks like it's because of the abbreviation, works with `Chicago, United States`.

**Comment by scottjl** [comment]
Ah, that fixed it. Thanks.

**Comment by xNinjaKittyx** [comment]
Is there a correct way to filter only by `name` in the filter by State? Some states in the US have the same city name.

Examples
- Portland https://geocoding-api.open-meteo.com/v1/search?name=Portland,%20United%20States&count=4&language=en&format=json
- Santa Clara https://geocoding-api.open-meteo.com/v1/search?name=Santa Clara,%20United%20States&count=4&language=en&format=json
