### ISSUE TITLE
Unable to retrieve stock data for stock codes containing "."

### ISSUE THREAD

**Issue by smurphboy** [glanceapp/glance#71]
An example is VMIG.L which is a valid Yahoo Finance stock code but which errors on startup saying nothing was returned.

Looking at the logs it appears to ignore the ".L" and searches for VMIG which is not a valid stock code.

**Comment by smurphboy** [comment]
Solved my own problem. Escape the stock code with single quote '.

So 'VMIG.L' works.

**Comment by svilenmarkov** [comment]
Hey, thanks for reporting this!

Quite odd, seems to work for me without having to wrap the symbol in quotes:

```yaml
- symbol: VMIG.L
  name: Vanguard
```

![image](https://github.com/glanceapp/glance/assets/7613769/15ec7147-4ca6-4803-a751-4e7c9c0370a2)

Good to know there's a workaround at least. I'll close this for now but feel free to leave a comment if you're having this issue again.
