### ISSUE TITLE
429 reddit

### ISSUE THREAD

**Issue by kapral18** [glanceapp/glance#78]
I got 100+ subscriptions and easily hit the request limit

![image](https://github.com/glanceapp/glance/assets/1625373/2b6b186c-3446-4064-b53e-baf6722089da)

Do you think adding random timeouts to each fetch can help? Or maybe allow to pass personal api key

**Comment by svilenmarkov** [comment]
Hey, thanks for reporting this!

For the time being the best I can suggest is splitting the subreddits into multiple pages so you don't hit them all at once. Realistically though, you're better off sticking to just a few that you care about the most as that was kind of the initial idea behind Glance.
