### ISSUE TITLE
Cant run docker image on windows

### ISSUE THREAD

**Issue by mgautam07** [glanceapp/glance#84]
Hi, I was trying to run the image on windows. I got this error in container logs "failed parsing config file: read glance.yml: is a directory" and status was Exited (1). 

I used this command 
``` docker run -d -p 8080:8080 -v ./glance.yml:/app/glance.yml  -v /etc/timezone:/etc/timezone:ro -v /etc/localtime:/etc/localtime:ro glanceapp/glance ```

Looks like a useful thing to have on my pc. Can't wait to try it.

**Comment by svilenmarkov** [comment]
Hey,

It looks like you forgot to create a `glance.yml` file before running the command so docker treated it as a directory instead. You'll have to delete that directory, create `glance.yml` and run the command again. You can use the contents of the [preconfigured page](https://github.com/glanceapp/glance/blob/main/docs/configuration.md#preconfigured-page) as a starting point for your `glance.yml` file.

**Comment by mgautam07** [comment]
I had a glance.yml file in the directory the issue was that windows uses ```\``` in file paths so I used this command
```bash
docker run -d -p 8080:8080 -v .\\glance.yml:/app/glance.yml  -v /etc/timezone:/etc/timezone:ro -v /etc/localtime:/etc/localtime:ro glanceapp/glance
```
Thanks
