### ISSUE TITLE
[Feature Request] More Small Columns

### ISSUE THREAD

**Issue by aryanmishra22** [glanceapp/glance#85]
Hello, I would like to request the ability to add more small columns. This is the way I am using glance right now and I would like to show more bookmarks to the right if possible. Thank you for your consideration.

![2024-05-19-181256_hyprshot](https://github.com/glanceapp/glance/assets/33474861/bc4a485d-60a0-4409-9950-27b77d414771)

**Comment by svilenmarkov** [comment]
Hey, thanks for the suggestion!

I don't plan on adding support for 4 small columns as that would introduce a bunch of complexity in terms of making the design responsive, though what you can do is use the new `dynamic-columns-experimental` style in each of your bookmark widgets and put them inside 2 `full` columns to achieve practically the same result. There's a demo of that in the release notes for [v0.4.0](https://github.com/glanceapp/glance/releases/tag/v0.4.0).
