### ISSUE TITLE
Can't start in Win

### ISSUE THREAD

**Issue by ncwuguo** [glanceapp/glance#98]
I download the releases file `glance-windows-amd64.exe.zip`, but when I click the file `.exe`,  a window flashes and it ends.

**Comment by ljf20122010** [comment]
> I download the releases file `glance-windows-amd64.exe.zip`, but when I click the file `.exe`, a window flashes and it ends.

me too

**Comment by ljf20122010** [comment]
> 我下载了发布文件，但是当我单击该文件时，一个窗口闪烁并结束。`glance-windows-amd64.exe.zip``.exe`

you can add the "glance.yml" to solve this problem

**Comment by svilenmarkov** [comment]
Hey, 

You must have a `glance.yml` configuration file in the directory where the executable is. You can grab a preconfigured file from [here](https://github.com/glanceapp/glance/blob/main/docs/configuration.md#preconfigured-page).
